version: '3'

services:
  flask-app:
    build: .
      # context: ./flask-app
    ports:
      - "5003:5000"
    depends_on:
      - mongodb
    # environment:
      #   MONGO_URI: mongodb://mongodb:27017/to-do-app  # Replace 'your-database-name'

  mongodb:
    image: mongo:latest
    ports:
      - "28017:28017" # Map host port to container port
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: