apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1  # You can adjust the number of replicas as needed.
  selector:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
      - name: flask-container
        image: sheenagarg9/to-do-app:latest
        ports:
        - containerPort: 5000  # Adjust the port as per your Flask app's configuration.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1  # You can adjust the number of replicas as needed.
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo:latest
        ports:
        - containerPort: 28017  # Adjust the port as per your Flask app's configuration.