apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-app-replication-controller
spec:
  replicas: 3
  selector:
    app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
      - name: flask-container
        image: sheenagarg9/to-do-app:latest

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb-replication-controller
spec:
  replicas: 3
  selector:
    app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo:latest
